export const LOGIN_START="LOGIN_START"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_ERROR="LOGIN_ERROR"

export const IS_LOGIN_START="IS_LOGIN_START"
export const IS_LOGIN_SUCCESS="IS_LOGIN_SUCCESS"
export const IS_LOGIN_ERROR="IS_LOGIN_ERROR"

export const LOAD_TABLES_START="LOAD_TABLES_START"
export const LOAD_TABLES_SUCCESS="LOAD_TABLES_SUCCESS"
export const LOAD_TABLES_ERROR="LOAD_TABLES_ERROR"

export const LOAD_CATEGORY_START="LOAD_CATEGORY_START"
export const LOAD_CATEGORY_SUCCESS="LOAD_CATEGORY_SUCCESS"
export const LOAD_CATEGORY_ERROR="LOAD_CATEGORY_ERROR"

export const LOAD_ITEM_START="LOAD_ITEM_START"
export const LOAD_ITEM_SUCCESS="LOAD_ITEM_SUCCESS"
export const LOAD_ITEM_ERROR="LOAD_ITEM_ERROR"

export const LOAD_ORDER_START="LOAD_ORDER_START"
export const LOAD_ORDER_SUCCESS="LOAD_ORDER_SUCCESS"
export const LOAD_ORDER_ERROR="LOAD_ORDER_ERROR"

export const DELETE_ORDER_START="DELETE_ORDER_START"
export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_ERROR="DELETE_ORDER_ERROR"

export const CREATE_ORDER_START="CREATE_ORDER_START"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_ERROR="CREATE_ORDER_ERROR"

export const UPDATE_ORDER_START="UPDATE_ORDER_START"
export const UPDATE_ORDER_SUCCESS="UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_ERROR="UPDATE_ORDER_ERROR"

export const MANAGER_ORDER_START="MANAGER_ORDER_START"
export const MANAGER_ORDER_SUCCESS="MANAGER_ORDER_SUCCESS"
export const MANAGER_ORDER_ERROR="MANAGER_ORDER_ERROR"

export const MANAGER_ORDER_UPDATE_START="MANAGER_ORDER_UPDATE_START"
export const MANAGER_ORDER_UPDATE_SUCCESS="MANAGER_ORDER_UPDATE_SUCCESS"
export const MANAGER_ORDER_UPDATE_ERROR="MANAGER_ORDER_UPDATE_ERROR"