export const LOAD_TABLES_START="LOAD_TABLES_START"
export const LOAD_TABLES_SUCCESS="LOAD_TABLES_SUCCESS"
export const LOAD_TABLES_ERROR="LOAD_TABLES_ERROR"

export const LOAD_CATEGORY_START="LOAD_CATEGORY_START"
export const LOAD_CATEGORY_SUCCESS="LOAD_CATEGORY_SUCCESS"
export const LOAD_CATEGORY_ERROR="LOAD_CATEGORY_ERROR"

export const LOAD_ITEM_START="LOAD_ITEM_START"
export const LOAD_ITEM_SUCCESS="LOAD_ITEM_SUCCESS"
export const LOAD_ITEM_ERROR="LOAD_ITEM_ERROR"

export const LOAD_ORDER_START="LOAD_ORDER_START"
export const LOAD_ORDER_SUCCESS="LOAD_ORDER_SUCCESS"
export const LOAD_ORDER_ERROR="LOAD_ORDER_ERROR"